### PR TITLE
Specify netbox packages

### PR DESCRIPTION
**Pull request by as0bu**
This allows users to specify/override the following parameters if needed:

- netbox_packages
- netbox_python_packages
- netbox_python_binary
- netbox_pip_binary
- netbox_ldap_packages

### CODE REVIEW

**Comment by lae** [comment]
@as0bu Could I have you rename the "private" variables to use a single leading underscore?

**Comment by lae** [comment]
@as0bu can you also rebase this against master?

**Comment by lae** [comment]
Hm, @as0bu are you familiar with rebases? They're not standard merges. You *will* need to force push after a rebase, because the gist is that rebases rewrite history. Take a look at this article: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

It may just be best to delete your branch locally, update your local master branch by pulling lae:master (fyi it's a lowercase L), recreate your branch off master and remake the changes. Make sure that your commit contains *just* the code you want me to merge, and then force push your branch and it should update this PR appropriately.

The current PR is not easily mergeable currently.

**Comment by as0bu** [comment]
@lae My apologies on the the name. I followed the instructions on the link you provided. Hopefully this is more aligned with what you're looking for. Let me know if there is anything I missed. Thanks!

**Comment by lae** [comment]
@as0bu Thanks.

`netbox_pip_binary` is deprecated since the removal of Python 2 support - could you drop that variable?

Also, per my earlier comment, could you use a single leading underscore instead of two? (like `_netbox_switch_ansible_python` was originally)

**Pull request merged**
