### PR TITLE
Install psycopg2-binary on RHEL systems

### LINKED ISSUE #51: Upgrade of psycopg2 dependency fails
I've been away on leave and when I returned last week I bumped netbox to the latest version, low and behold its failed to deploy psycopg2 python package, where before its been fine.

It appears that pg_config can't be found  when pip goes to install psycopg2.  Looking back at my previous successful deploys it was using v0.7.6 of this role.  changes seem to indicate that psycopg2 was added in 0.7.7

Ive been trying to track down source of this issue and see that  pg_config is installed on the target machine and available from command shell, yet doesn't appear to be available to pip3?

```
TASK [lae.netbox : Install psycopg2/selinux via pip on Red Hat-based distros] ***
[DEPRECATION WARNING]: Invoking "pip" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `name: "{{ item }}"`, please use `name: ['psycopg2', 'selinux']`
 and remove the loop. This feature will be removed in version 2.11. Deprecation
 warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
failed: [stg001] (item=['psycopg2', 'selinux']) => {"changed": false, "cmd": ["/usr/local/bin/pip3", "install", "-U", "psycopg2", "selinux"], "item": ["psycopg2", "selinux"], "msg": "stdout: Collecting psycopg2\n  Using cached https://files.pythonhosted.org/packages/23/7e/93c325482c328619870b6cd09370f6dbe1148283daca65115cd63642e60f/psycopg2-2.8.2.tar.gz\n    Complete output from command python setup.py egg_info:\n    running egg_info\n    creating pip-egg-info/psycopg2.egg-info\n    writing pip-egg-info/psycopg2.egg-info/PKG-INFO\n    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt\n    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt\n    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'\n    \n    Error: pg_config executable not found.\n    \n    pg_config is required to build psycopg2 from source.  Please add the directory\n    containing pg_config to the $PATH or specify the full executable path with the\n    option:\n    \n        python setup.py build_ext --pg-config /path/to/pg_config build ...\n    \n    or with the pg_config option in 'setup.cfg'.\n    \n    If you prefer to avoid building psycopg2 from source, please install the PyPI\n    'psycopg2-binary' package instead.\n    \n    For further information please check the 'doc/src/install.rst' file (also at\n    <http://initd.org/psycopg/docs/install.html>).\n    \n    \n    ----------------------------------------\n\n:stderr: Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-install-gwcflx76/psycopg2/\n
```

### PR DESCRIPTION
**Pull request by madeinoz67**
I'm finding this is working for me on production system I was having issues with.

fixes #51

### CODE REVIEW

**Comment by lae** [comment]
looks like there's a consistent failure on connecting to netbox for netbox stable deployments on ubuntu 18, but no failure during the actual run. CI wasn't outputting logs before running actual tests (so the failure on ubuntu caused logs to not be output for it) so I just committed a fix for that, now I'm rerunning the build (and hopefully the logs will have something).

**Comment by madeinoz67** [comment]
I did see that the master was failing just after I had forked forked.   I normally use gitlab for my CI builds internally so Travis is all smoke and mirrors to me atm haha, is there a way to set-up a local dev environment and yes the build locally?  how do you currently go about testing the build locally?

**Comment by lae** [comment]
There is a `Vagrantfile` in the top folder. If you don't use Vagrant, check https://www.vagrantup.com/ for install instructions. `vagrant up` should both bring up a VM and provision it (i.e. run the playbook), `vagrant provision` just does the provision, in case it failed, and `vagrant stop && vagrant destroy` will stop and delete the VM. The definition in the `Vagrantfile` uses Debian 9 but you can change that image to another, so Ubuntu Bionic for the failing test I guess.

**Comment by lae** [comment]
Realised this while implementing a Vagrantfile for a work project - it requires that you symlink `~/.ansible/roles/lae.netbox` to your development copy (or that you have it checked out at that location).

**Comment by lae** [comment]
I'm so dumb LOL. I forgot that molecule was added into the role a while back (and actually, this was contributed by you!):

https://github.com/lae/ansible-role-netbox/blob/master/DEVELOPING.md

Just have to add a note to the README about it, I guess.

**Comment by lae** [comment]
todo before merging: test that an existing functional installation with `psycopg2` still works when a role with this change is applied (have to do manually)

The Ubuntu 18 failures seem to be unrelated, which I opened #59 for.

**Pull request merged**
