### PR TITLE
Add tests using molecule with vagrant

### PR DESCRIPTION
**Pull request by madeinoz67**
Adds vagrant molecule to make locally testing with vagrant much easier and cleaner

Requires molecule to be installed

### CODE REVIEW

**Comment by lae** [comment]
I think builds failed because upstream pushed a commit right in between the deploy and idempotency test. Lucky.

**Comment by madeinoz67** [comment]
Forgot to mention that Ive disabled lint checks in this PR as was throwing up a number or errors throughout the code which is out of scope of the PR to fix them.  

Lint tests can be re-enabled in molecule.yml under their relevant sections
e.g.

```yaml
lint:
  name: yamllint
  enabled: true
```

```yaml
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
    enabled: true
```

**Comment by lae** [comment]
* Can you add a `DEVELOPING.md` that discusses briefly how to setup and run this test environment?
* The `.gitignore` is pretty unwieldy. What files do you actually have in your dev environment that you need to ignore? `.vscode/*`? (afaict the only lines relevant to this repo are `.vagrant`).
* Does `molecule/` need to be a top level directory or does it make sense to move it into the `tests/` directory?

**Comment by madeinoz67** [comment]
@lae can do not a problem.

I develop in vscode and its part of my standard .gitignore so I don't commit anything I shouldn't but can be removed.

molecule needs to be as it is currently set as when running tests you run from the root of the role.

e.g. molecule test

All tests reside in the molecule/scenarios/test, in this case a single "default" scenario. 

Other scenarios can be added at anytime in the future using molecule init scenario .....

**Comment by madeinoz67** [comment]
@lae please review DEVELOPING.md to see it its what you want

**Comment by lae** [comment]
Commits were cherry-picked and merged.

**Pull request closed without merging**
